SimpleCRM/SimpleCRM/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

SimpleCRM/urls.py
'''
App root

'''

#django imports
# from django.conf import settings
from . import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import django.contrib.auth.urls
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/mycrm/login')),
    #crm dashboard
    url(r'^mycrm/', include('mycrm.urls')),
    #password reset pages
    url(r'^accounts/', include('django.contrib.auth.urls')),
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mycrm/urls.py
'''
mycrm urls
'''

#core Django imports
from django.conf.urls import url
from django.contrib.auth import views as auth_views

#Import from current app
from . import views

app_name = 'mycrm'

urlpatterns=[
    #login views
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registration/password_reset_form.html'}, name='password_reset'),
    url(r'^logout/$', views.logout_crm, name="logout"),
    #mycrm views
    url(r'^$', views.UsersList.as_view(), name="home"),
    url(r'^user/$', views.UsersList.as_view(), name="user"),
    url(r'^user/(?P<pk>[0-9]+)/edit$', views.UserEdit.as_view(), name="user_edit"),
    url(r'^user/(?P<pk>[0-9]+)/delete$', views.UserDelete.as_view(), name="user_delete"),
    url(r'^user/register$', views.RegisterUser.as_view(), name="register"),
    #company views
    url(r'^company/$', views.CompaniesListView.as_view(), name="company"),
    url(r'^company/add$', views.CompanyAdd.as_view(), name="company_add"),
    url(r'^company/(?P<pk>[0-9]+)/$', views.CompanyDetailView.as_view(), name="detail"),
    url(r'^company/(?P<pk>[0-9]+)/edit/$', views.CompanyUpdate.as_view(), name="company_edit"),
    url(r'^company/(?P<pk>[0-9]+)/delete/$', views.CompanyDelete.as_view(), name="company_delete"),
    #TODO add company pk here...
    # url(r'^company/addcontact', views.ContactAdd.as_view(), name="contact_add"),
    url(r'^company/(?P<pk>[0-9]+)/addcontact', views.ContactAdd.as_view(), name="contact_add"),
    url(r'^company/(?P<pk>[0-9]+)/editcontact', views.ContactEdit.as_view(), name="edit_contact"),
    url(r'^company/(?P<pk>[0-9]+)/deletecontact', views.ContactDelete.as_view(), name="delete_contact"),
    #TODO add company pk here
    # url(r'^company/addorder', views.OrderAdd.as_view(), name="order_add"),
    url(r'^company/(?P<pk>[0-9]+)/addorder', views.OrderAdd.as_view(), name="order_add"),    
    url(r'^company/(?P<pk>[0-9]+)/orderedit', views.OrderEdit.as_view(), name="order_edit"),
    url(r'^company/report$', views.company_report, name="company_report"),
]

mycrm/models.py
'''
Database models for mycrm
'''
#core Django imports
from django.db import models
from django.contrib.auth.models import User

#local imports
from .validators import validate_phone


class Company(models.Model):
    '''
    Company data, display on company list
    '''
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=4500)
    picture = models.CharField(max_length=500, null=True, default=None)
    # picture = models.ImageField(upload_to="images", blank=True, null=True) #picture field change require delete whole database
    ranking_position = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.name

class Comment(models.Model):
    '''
    Company comment
    related to user and company
    '''
    title = models.CharField(max_length=128, default=None)
    comment = models.TextField(max_length=4000)

    #current time when coment post
    date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User)
    company = models.ForeignKey(Company)

    def __str__(self):
        return self.title

class BusinessCard(models.Model):
    '''
    Business card has user data corresponding to company
    '''
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    phone = models.CharField(max_length=20, validators=[validate_phone])
    company = models.ForeignKey(Company)

    class Meta:
        verbose_name = 'Business Card'
        verbose_name_plural = 'Business Cards'

    def __str__(self):
        return self.name


class Order(models.Model):
    '''
    Order has all orders corresponding to one company. Company can have many orders
    '''
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=2000)
    value = models.DecimalField(max_digits=12, decimal_places=2) #value in euro
    payment_status = models.BooleanField(default=False) #true if client already pait us for order
    date_created = models.DateField() #date created
    project_is_finished = models.BooleanField(default=False) #tells if project is finished
    company = models.ForeignKey(Company) #for who we make project

    @property
    def sum_quantity(self):
        '''
        calculate all bills sum, total display on companies list view
        '''
        total=sum([obj.value for obj in Order.objects.filter(company=self.company.pk)])
        return total

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return self.name

mycrm/views.py
'''
mycrm all views
'''

#core Django imports
from django.contrib import messages
from django.contrib.sessions.backends.db import SessionStore
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth import logout
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Coalesce

#Import from current app
import mycrm.models as models
import mycrm.forms as forms
from logger import logger, logger_user_activity

#Third party libraries import
from reportlab.pdfgen import canvas

#my utilities and libraries
from mycrm.my_utilities import queries, breadcrumb_creator


session = SessionStore()


class UpdateViewWithMessage(UpdateView):
    '''
    Extended Update view contain field:
    my_message - message which displays in green bracket after succesfull delete, user must first set this field
    page_title - title that dispalys in update page header
    '''
    def form_valid(self, form):
        messages.success(self.request, self.my_message)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        #using for create universal template for update views
        context = super().get_context_data()
        context['page_title'] = self.page_title
        return context

class DeleteViewWithMessage(DeleteView):
    '''
    Extended Delete view contain field:
    my_message - message which displays in green bracket after succesfull delete, user must first set this field
    page_title - title that dispalys in update page header
    page_text - text display below page title in <p>page_text</p>
    '''
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.my_message)
        return super().delete(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['page_title'] = self.page_title
        context['page_text'] = '{} {}?'.format(self.page_text, context['object'])
        return context


class CreateViewWithMessage(CreateView):
    '''
    Create view with green popup message after success submit
    Child must overrdte my_message
    '''

    def form_valid(self, form):
        messages.success(self.request, self.my_message)
        return super().form_valid(form)


@login_required
def logout_crm(request):
    '''
    logout current user
    /mycrm/logout
    '''
    logout(request)
    return redirect('mycrm:login')


@login_required
def company_report(request):
    '''
    create pdf report
    company/report
    '''
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'
    p = canvas.Canvas(response, initialFontName='Times-Roman')
    lines = queries.get_companies_report_text()

    page_size = 35
    space = 20
    for i,line in enumerate(lines):
        p.drawString(50, 800-(i % page_size)*space, line)
        if (i+1) % page_size == 0:
            p.showPage()
    p.save()
    return response


class UsersList(LoginRequiredMixin, ListView):
    '''
    page with users table
    mycrm/user/
    '''
    template_name = 'user/user.html'
    context_object_name = 'users'
    model = User


class RegisterUser(LoginRequiredMixin, CreateViewWithMessage):
    '''
    registration page
    mycrm/user/register
    '''
    form_class = forms.SignUpForm
    model = User #user from django
    template_name = 'mycrm/user_register.html'
    success_url = reverse_lazy('mycrm:user')
    my_message = 'User created succesfully!'

class UserEdit(LoginRequiredMixin, PermissionRequiredMixin, UpdateViewWithMessage):
    '''
    user edit page
    mycrm/user/<user_id>/edit
    '''
    permission_required = 'auth.change_user'
    form_class = forms.EditUserForm
    model = User
    template_name = 'mycrm/update_view.html'
    success_url = reverse_lazy('mycrm:user')
    my_message = 'Update user succesfully'
    page_title = 'Edit User:'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('Home', reverse_lazy('mycrm:home'))
        breadcrumb.append_page('User', reverse_lazy('mycrm:user'))
        breadcrumb.append_active_page('Edit User')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context



class UserDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteViewWithMessage):
    '''
    user delete page
    mycrm/user/<user_id>/delete
    '''
    permission_required = 'auth.delete_user'
    model = User
    template_name = 'mycrm/delete_view.html'
    success_url = reverse_lazy('mycrm:user')
    my_message = 'You delete user succesfully!'
    page_title = 'Delete user'
    page_text = 'Are you sure delete user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('User', reverse_lazy('mycrm:user'))
        breadcrumb.append_active_page('Delete User')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context

class CompaniesListView(LoginRequiredMixin, ListView):
    '''
    page with companies table
    mycrm/company
    '''
    model = models.Company
    template_name = 'mycrm/company.html'

    def get_context_data(self, **kwargs):
        context = super(CompaniesListView, self).get_context_data(**kwargs)
        context['tomek']= 'przyklad'
        return context

    def get_queryset(self): # for filtering
        '''
        Using for filtering (search filed)
        :return: filtered queryset
        '''
        qs= super().get_queryset()
        var = self.request.GET.get('q')
        if var:
            return qs.filter(name__startswith=var)
        return qs


class CompanyUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateViewWithMessage):
    '''
    company update page
    mycrm/company/<company_id>/edit
    '''
    permission_required = 'mycrm.change_company'
    form_class = forms.CompanyForm
    model = models.Company
    template_name = 'mycrm/update_view.html'
    success_url = reverse_lazy('mycrm:company')
    my_message = 'You change company data succesfully!'
    page_title = 'Edit company:'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('Home', reverse_lazy('mycrm:home'))
        breadcrumb.append_page('Company', reverse_lazy('mycrm:company'))
        breadcrumb.append_active_page('Edit Company')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context


class CompanyDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteViewWithMessage):
    '''
    company delete page
    mycrm/<company_id>/delete
    '''
    permission_required = 'mycrm.delete_company'
    model = models.Company
    success_url = reverse_lazy('mycrm:company')
    template_name = 'mycrm/delete_view.html'
    page_title = 'Delete company'
    page_text = 'Are you sure you want delete company:'
    my_message = 'You delete company succesfully!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('Home', reverse_lazy('mycrm:home'))
        breadcrumb.append_page('Company', reverse_lazy('mycrm:company'))
        breadcrumb.append_active_page('Delete Company')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context


class CompanyDetailView(LoginRequiredMixin, DetailView):
    '''
    company detail view:
    description, contacts table, orders table
    comments - variable ith all comments sorted by date
    has count variables for using in template:
    comments_count
    contacts_count
    order_count
    mycrm/company/<company_id>/

    '''
    model = models.Company
    template_name = 'mycrm/company_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['comments'] = models.Comment.objects.all()
        current_company = context['object']
        nonordered_comments = current_company.comment_set.all()
        context['comments'] = nonordered_comments.order_by(Coalesce('date', 'pk').desc())
        context['comments_count'] = current_company.comment_set.count()
        context['contacts_count'] = current_company.businesscard_set.count()
        context['order_count'] = current_company.order_set.count()
        logger.info(context['comments'])
        return context

    def get(self, request, *args, **kwargs):
        get = request.GET
        if get and 'comm' in get and 'title' in get:
            logger.info('ADDING COMMENT ...')
            logger.info('REQEST ->   {}'.format(request))
            logger.info('kwargs  {} user {} args {}'.format(kwargs, request.user, args))
            title = request.GET['title']
            comm = request.GET['comm']
            current_company = models.Company.objects.get(pk=kwargs['pk'])
            # current_company = self.get_context_data()['object'] #not works
            #pk mam w request current_company.comment_set - comment_set.comment - wyciągam coś z comment
            comment = models.Comment(company=current_company, user=request.user, title=title, comment=comm)
            comment.save()
            logger.info('comment content :{}'.format(comment))

        if get and 'delete_comment' in get:
            logger.info('DELETING COMMENT ...')

mycrm/templates/mycrm/company.html
{% extends 'base.html' %}
{% block breadcrumb %}

        <li class="breadcrumb-item"><a href="{% url 'mycrm:home' %}">Home</a></li>
        <li class="breadcrumb-item active">Company</li>
    
{% endblock %}

{% block content %}

<!-- Example DataTables Card-->
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Companies table:</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Total orders value</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Total orders value</th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for company in object_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ company.name }}</td>
                            <td>
                                {% if company.order_set.last.sum_quantity %}
                                {{ company.order_set.last.sum_quantity }}
                                {% else %}0.00
                                {% endif %}
                                <i class="fa fa-eur" aria-hidden="true"></i></td>
                                <td>
                                    <a class="btn btn-light" href="{% url 'mycrm:detail' company.pk %}">Details <i class="fa fa-address-card-o" aria-hidden="true"></i></a>
                                    <a class="btn btn-primary" href="{% url 'mycrm:company_edit' company.pk %}" role="button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                    <a class="btn btn-primary" href="{% url 'mycrm:company_delete' company.pk %}" role="button"><i class="fa fa-trash" aria-hidden="true"></i></a>
                                    
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
        
        
        {% endblock %}
        

mycrm/templates/mycrm/company_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{% url 'mycrm:home' %}">Home</a></li>
<li class="breadcrumb-item active"><a href="{% url 'mycrm:company' %}">Company</a></li>
<li class="breadcrumb-item active">Add</li>

{% endblock %}

{% block content %}

<div class="container">
        <div class="card mx-auto mt-5">
          <div class="card-header">Add new company</div>
          <div class="card-body">
                <form method="post" action="" id="id-exampleForm" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Submit" class="btn btn-primary"/>
                    </form>
                <div class="text-center">
            </div>
          </div>
        </div>
      </div>
    
{% endblock %}

mycrm/templates/mycrm/company_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}

<style>
        
        .nav .nav-tabs {
            font-family: Arial;
            color: blue;
        }
        
        /* comment style on comments page */
        
        .comment{
            background-color: #646464;
            color: #ffffff;
            /* Top Right Bottom Left */
            padding: 4% 6% 5% 4%;
            font-family: Arial;
            margin: 10px;
            border: 2px solid rgb(199, 199, 199);
            /* round border */
            border-radius: 6px;
        }

        .comment .modal{
            color: rgb(44, 44, 44);
        }
        
        .secondary {
            background: none;
            color: #d4e7ff;
            padding-top: 8%;
        }
        
        .delete-form{
            padding-top: 2%;
            padding-left: 85%;
        }
        
        .comment-form{
            margin: 10px;
            padding-bottom: 30px;
        }





        /*Style for about company*/
        .mylogo{
            width: 280px;
            margin-right: 20px;
            margin-bottom: 20px;
            float: left;
        }
        
        .mycompany{
            min-width: 400px;
            min-height: 290px;
        }
        
        /*
        .mylogo2{
            background-color: magenta;
            align-self: center;
        }
        */
        .cardEmployers{
            width: 370px;
            margin: 20px;
        
            float: right;
        }
        
        .graybg{
            background-color: lightgray;
        }
        
    </style>
    
{% endblock %}

{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{% url 'mycrm:home' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'mycrm:company' %}">Company</a></li>
<li class="breadcrumb-item active">Details</li>

{% endblock %}

{% block content %}


<div class="container-fluid">

<div class="tabs">

<div class="row">
        <!-- Colorful tabs -->
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-user"></i>
                    </div>
                    <div class="mr-5">About</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="#about">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                    </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-list"></i>
                    </div>
                    <div class="mr-5">{{ contacts_count }} Contacts</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="#contacts">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                    </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-shopping-cart"></i>
                    </div>
                    <div class="mr-5">{{ order_count }} Orders</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="#orders">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                    </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
                
                <div class="card text-white bg-danger o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fa fa-fw fa-comment"></i>
                        </div>
                        <div class="mr-5">{{ comments_count }} Comments</div>
                    </div>
                    <a class="card-footer text-white clearfix small z-1" href="#comments">
                        <span class="float-left">View Details</span>
                        <span class="float-right">
                            <i class="fa fa-angle-right"></i>
                        </span>
                    </a>
                </div></div>
    </div>
    <!-- Panels content -->
    <div class="tab-content">
        <div id="about" class="tab active">
            {% include "mycrm/includes/_about_tab.html" %}
        </div>
        
        <div id="contacts" class="tab">
                {% include "mycrm/includes/_contacts_tab.html" %}
        </div>
        <div id="orders" class="tab">
                {% include "mycrm/includes/_orders_tab.html" %}
        </div>
        <div id="comments" class="tab">
                {% include "mycrm/includes/_comments_tab.html" %}
        </div>
    </div>

</div> <!-- tabs -->
     
    
</div>
    {% endblock %}

    {% block js %}
    {% comment %} using for switching tabs {% endcomment %}
    <script>
        jQuery(document).ready(function() {
            //first show only about
            jQuery('.tabs ' + '#about').show().siblings().hide();
            jQuery('a').on('click', function(e)  {
                var currentAttrValue = jQuery(this).attr('href');
            
                // Show/Hide Tabs
                jQuery('.tabs ' + currentAttrValue).show().siblings().hide();
            
                // Change/remove current tab to active
                jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
            
                e.preventDefault();
                console.log('curr:'+currentAttrValue);
            });


            /*Need to activete all tables with class table*/
            $('.table').DataTable();


            //get id from button and pass it to message box
            $('.deleteval').click( function(e){
                var at = $(this).attr('value');
                $('.deletebutton').val(at)
                //console.log('click delete'+at+' '+deletebutton);
            });
            


            
        });


    </script>
    {% endblock %}

mycrm/templates/mycrm/company_detail_add_contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{% url 'mycrm:home' %}">Home</a></li>
<li class="breadcrumb-item active"><a href="{% url 'mycrm:company' %}">Company</a></li>
<li class="breadcrumb-item active">Add contact</li>

{% endblock %}

{% block content %}
<!-- add contact form -->
<div class="container">
        <div class="card mx-auto mt-5">
          <div class="card-header">{{ page_title }}</div>
          <div class="card-body">
                <form method="post" action="" id="id-exampleForm">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Add" class="btn btn-primary"/>
                    </form>
                <div class="text-center">
            </div>
          </div>
        </div>
      </div>
    
{% endblock %}

mycrm/templates/mycrm/company_detail_add_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{% url 'mycrm:home' %}">Home</a></li>
<li class="breadcrumb-item active"><a href="{% url 'mycrm:company' %}">Company</a></li>
<li class="breadcrumb-item active">Add order</li>

{% endblock %}

{% block content %}
<!-- Company add order form -->
<div class="container">
        <div class="card mx-auto mt-5">
          <div class="card-header">{{ page_title }}</div>
          <div class="card-body">
                <form method="post" action="" id="id-exampleForm"  enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Add" class="btn btn-primary"/>
                    </form>
                <div class="text-center">
            </div>
          </div>
        </div>
      </div>
    
{% endblock %}

mycrm/templates/mycrm/delete_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumb  %}

<!--<li class="breadcrumb-item"><a href="{% url 'mycrm:home' %}">Home</a></li>-->
<!--<li class="breadcrumb-item">Users</li>-->
<!--<li class="breadcrumb-item active">Delete</li>-->

{{ breadcrumb|safe }}

{% endblock %}

{% block content %}



<div class="container">
        <div class="card mx-auto mt-5">
          <div class="card-header">{{ page_title }}</div>
          <div class="card-body">
                <p>{{ page_text }}</p>
                <form method="post" action="" id="id-exampleForm">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Delete" class="btn btn-danger"/>
                    </form>
                <div class="text-center">
            </div>
          </div>
        </div>
      </div>
    
{% endblock %}

mycrm/templates/mycrm/update_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumb %}

<!--<li class="breadcrumb-item"><a href="{% url 'mycrm:home' %}">Home</a></li>-->
<!--<li class="breadcrumb-item">User</li>-->
<!--<li class="breadcrumb-item active">Update</li>-->

{{ breadcrumb|safe }}

{% endblock %}

{% block content %}

<div class="container">
        <div class="card mx-auto mt-5">
          <div class="card-header">{{ page_title }}</div>
          <div class="card-body">
                <form method="post" action="" id="id-exampleForm" enctype="multipart/form-data" class="form1">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Update" class="btn btn-primary"/>
                    </form>
                <div class="text-center">
            </div>
          </div>
        </div>
      </div>
    
{% endblock %}

mycrm/templates/mycrm/user_register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{% url 'mycrm:home' %}">Home</a></li>
<li class="breadcrumb-item active"><a href="{% url 'mycrm:user' %}">User</a></li>
<li class="breadcrumb-item active">Register</li>

{% endblock %}

{% block content %}

<div class="container">
        <div class="card mx-auto mt-5">
          <div class="card-header">Register new user:</div>
          <div class="card-body">
                <p>{{ page_text }}</p>
                <form method="post" action="" id="id-exampleForm">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Register" class="btn btn-primary"/>
                    </form>
                <div class="text-center">
            </div>
          </div>
        </div>
      </div>
    
{% endblock %}