SimpleCRM/SimpleCRM/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

SimpleCRM/urls.py
'''
App root

'''

#django imports
# from django.conf import settings
from . import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import django.contrib.auth.urls
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/mycrm/login')),
    #crm dashboard
    url(r'^mycrm/', include('mycrm.urls')),
    #password reset pages
    url(r'^accounts/', include('django.contrib.auth.urls')),
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mycrm/urls.py
'''
mycrm urls
'''

#core Django imports
from django.conf.urls import url
from django.contrib.auth import views as auth_views

#Import from current app
from . import views

app_name = 'mycrm'

urlpatterns=[
    #login views
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registration/password_reset_form.html'}, name='password_reset'),
    url(r'^logout/$', views.logout_crm, name="logout"),
    #mycrm views
    url(r'^$', views.UsersList.as_view(), name="home"),
    url(r'^user/$', views.UsersList.as_view(), name="user"),
    url(r'^user/(?P<pk>[0-9]+)/edit$', views.UserEdit.as_view(), name="user_edit"),
    url(r'^user/(?P<pk>[0-9]+)/delete$', views.UserDelete.as_view(), name="user_delete"),
    url(r'^user/register$', views.RegisterUser.as_view(), name="register"),
    #company views
    url(r'^company/$', views.CompaniesListView.as_view(), name="company"),
    url(r'^company/add$', views.CompanyAdd.as_view(), name="company_add"),
    url(r'^company/(?P<pk>[0-9]+)/$', views.CompanyDetailView.as_view(), name="detail"),
    url(r'^company/(?P<pk>[0-9]+)/edit/$', views.CompanyUpdate.as_view(), name="company_edit"),
    url(r'^company/(?P<pk>[0-9]+)/delete/$', views.CompanyDelete.as_view(), name="company_delete"),
    #TODO add company pk here...
    # url(r'^company/addcontact', views.ContactAdd.as_view(), name="contact_add"),
    url(r'^company/(?P<pk>[0-9]+)/addcontact', views.ContactAdd.as_view(), name="contact_add"),
    url(r'^company/(?P<pk>[0-9]+)/editcontact', views.ContactEdit.as_view(), name="edit_contact"),
    url(r'^company/(?P<pk>[0-9]+)/deletecontact', views.ContactDelete.as_view(), name="delete_contact"),
    #TODO add company pk here
    # url(r'^company/addorder', views.OrderAdd.as_view(), name="order_add"),
    url(r'^company/(?P<pk>[0-9]+)/addorder', views.OrderAdd.as_view(), name="order_add"),    
    url(r'^company/(?P<pk>[0-9]+)/orderedit', views.OrderEdit.as_view(), name="order_edit"),
    url(r'^company/report$', views.company_report, name="company_report"),
]

mycrm/forms.py
'''
Forms using in mycrm app
'''
#core Django imports
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Div, HTML, Submit, BaseInput, Button, Field
from django import forms
import django.contrib.auth.models as auth_models
import django.contrib.auth.forms as auth_forms

#Import from app
from .models import Company, BusinessCard, Order

class CompanyForm(forms.ModelForm):
    '''
    Form using in CompanyUpdate and CompanyAdd views. User add new company
    '''
    class Meta:
        model = Company
        fields=['name', 'description', 'picture']


class SignUpForm(auth_forms.UserCreationForm):
    '''
    Form using for reginster new user in mycrm,
    mycrm/user/register
    '''
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    class Meta:
        model = auth_models.User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class EditUserForm(forms.ModelForm):
    '''
    Form using in UserEdit view. Edits User django model, can change password login and other data
    mycrm/user/<user_id>/edit
    '''
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')

    class Meta:
        model = auth_models.User
        fields = ('username', 'first_name', 'last_name', 'email')


class ContactAddForm(forms.ModelForm):
    '''
    Using for ContactAdd and ContactEdit views. Company contact editing or add
    mycrm/company/<pk>/addcontact
    mycrm/company/<contact_id>/editcontact
    '''
    class Meta:
        model = BusinessCard
        fields=['name', 'last_name', 'phone'] #company add automaticley

class OrderAddForm(forms.ModelForm):
    '''
    Using in OrderAdd and OrderEdit. Can add/edit contact to form
    mycrm/company/addcontact
    mycrm/company/<contact_id>/orderedit
    '''
    class Meta:
        model = Order
        fields=['name', 'description', 'value', 'payment_status','date_created','project_is_finished'] #company field update automacicly

mycrm/views.py
'''
mycrm all views
'''

#core Django imports
from django.contrib import messages
from django.contrib.sessions.backends.db import SessionStore
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth import logout
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Coalesce

#Import from current app
import mycrm.models as models
import mycrm.forms as forms
from logger import logger, logger_user_activity

#Third party libraries import
from reportlab.pdfgen import canvas

#my utilities and libraries
from mycrm.my_utilities import queries, breadcrumb_creator


session = SessionStore()


class UpdateViewWithMessage(UpdateView):
    '''
    Extended Update view contain field:
    my_message - message which displays in green bracket after succesfull delete, user must first set this field
    page_title - title that dispalys in update page header
    '''
    def form_valid(self, form):
        messages.success(self.request, self.my_message)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        #using for create universal template for update views
        context = super().get_context_data()
        context['page_title'] = self.page_title
        return context

class DeleteViewWithMessage(DeleteView):
    '''
    Extended Delete view contain field:
    my_message - message which displays in green bracket after succesfull delete, user must first set this field
    page_title - title that dispalys in update page header
    page_text - text display below page title in <p>page_text</p>
    '''
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.my_message)
        return super().delete(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['page_title'] = self.page_title
        context['page_text'] = '{} {}?'.format(self.page_text, context['object'])
        return context


class CreateViewWithMessage(CreateView):
    '''
    Create view with green popup message after success submit
    Child must overrdte my_message
    '''

    def form_valid(self, form):
        messages.success(self.request, self.my_message)
        return super().form_valid(form)


@login_required
def logout_crm(request):
    '''
    logout current user
    /mycrm/logout
    '''
    logout(request)
    return redirect('mycrm:login')


@login_required
def company_report(request):
    '''
    create pdf report
    company/report
    '''
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'
    p = canvas.Canvas(response, initialFontName='Times-Roman')
    lines = queries.get_companies_report_text()

    page_size = 35
    space = 20
    for i,line in enumerate(lines):
        p.drawString(50, 800-(i % page_size)*space, line)
        if (i+1) % page_size == 0:
            p.showPage()
    p.save()
    return response


class UsersList(LoginRequiredMixin, ListView):
    '''
    page with users table
    mycrm/user/
    '''
    template_name = 'user/user.html'
    context_object_name = 'users'
    model = User


class RegisterUser(LoginRequiredMixin, CreateViewWithMessage):
    '''
    registration page
    mycrm/user/register
    '''
    form_class = forms.SignUpForm
    model = User #user from django
    template_name = 'mycrm/user_register.html'
    success_url = reverse_lazy('mycrm:user')
    my_message = 'User created succesfully!'

class UserEdit(LoginRequiredMixin, PermissionRequiredMixin, UpdateViewWithMessage):
    '''
    user edit page
    mycrm/user/<user_id>/edit
    '''
    permission_required = 'auth.change_user'
    form_class = forms.EditUserForm
    model = User
    template_name = 'mycrm/update_view.html'
    success_url = reverse_lazy('mycrm:user')
    my_message = 'Update user succesfully'
    page_title = 'Edit User:'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('Home', reverse_lazy('mycrm:home'))
        breadcrumb.append_page('User', reverse_lazy('mycrm:user'))
        breadcrumb.append_active_page('Edit User')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context



class UserDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteViewWithMessage):
    '''
    user delete page
    mycrm/user/<user_id>/delete
    '''
    permission_required = 'auth.delete_user'
    model = User
    template_name = 'mycrm/delete_view.html'
    success_url = reverse_lazy('mycrm:user')
    my_message = 'You delete user succesfully!'
    page_title = 'Delete user'
    page_text = 'Are you sure delete user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('User', reverse_lazy('mycrm:user'))
        breadcrumb.append_active_page('Delete User')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context

class CompaniesListView(LoginRequiredMixin, ListView):
    '''
    page with companies table
    mycrm/company
    '''
    model = models.Company
    template_name = 'mycrm/company.html'

    def get_context_data(self, **kwargs):
        context = super(CompaniesListView, self).get_context_data(**kwargs)
        context['tomek']= 'przyklad'
        return context

    def get_queryset(self): # for filtering
        '''
        Using for filtering (search filed)
        :return: filtered queryset
        '''
        qs= super().get_queryset()
        var = self.request.GET.get('q')
        if var:
            return qs.filter(name__startswith=var)
        return qs


class CompanyUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateViewWithMessage):
    '''
    company update page
    mycrm/company/<company_id>/edit
    '''
    permission_required = 'mycrm.change_company'
    form_class = forms.CompanyForm
    model = models.Company
    template_name = 'mycrm/update_view.html'
    success_url = reverse_lazy('mycrm:company')
    my_message = 'You change company data succesfully!'
    page_title = 'Edit company:'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('Home', reverse_lazy('mycrm:home'))
        breadcrumb.append_page('Company', reverse_lazy('mycrm:company'))
        breadcrumb.append_active_page('Edit Company')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context


class CompanyDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteViewWithMessage):
    '''
    company delete page
    mycrm/<company_id>/delete
    '''
    permission_required = 'mycrm.delete_company'
    model = models.Company
    success_url = reverse_lazy('mycrm:company')
    template_name = 'mycrm/delete_view.html'
    page_title = 'Delete company'
    page_text = 'Are you sure you want delete company:'
    my_message = 'You delete company succesfully!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('Home', reverse_lazy('mycrm:home'))
        breadcrumb.append_page('Company', reverse_lazy('mycrm:company'))
        breadcrumb.append_active_page('Delete Company')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context


class CompanyDetailView(LoginRequiredMixin, DetailView):
    '''
    company detail view:
    description, contacts table, orders table
    comments - variable ith all comments sorted by date
    has count variables for using in template:
    comments_count
    contacts_count
    order_count
    mycrm/company/<company_id>/

    '''
    model = models.Company
    template_name = 'mycrm/company_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['comments'] = models.Comment.objects.all()
        current_company = context['object']
        nonordered_comments = current_company.comment_set.all()
        context['comments'] = nonordered_comments.order_by(Coalesce('date', 'pk').desc())
        context['comments_count'] = current_company.comment_set.count()
        context['contacts_count'] = current_company.businesscard_set.count()
        context['order_count'] = current_company.order_set.count()
        logger.info(context['comments'])
        return context

    def get(self, request, *args, **kwargs):
        get = request.GET
        if get and 'comm' in get and 'title' in get:
            logger.info('ADDING COMMENT ...')
            logger.info('REQEST ->   {}'.format(request))
            logger.info('kwargs  {} user {} args {}'.format(kwargs, request.user, args))
            title = request.GET['title']
            comm = request.GET['comm']
            current_company = models.Company.objects.get(pk=kwargs['pk'])
            # current_company = self.get_context_data()['object'] #not works
            #pk mam w request current_company.comment_set - comment_set.comment - wyciągam coś z comment
            comment = models.Comment(company=current_company, user=request.user, title=title, comment=comm)
            comment.save()
            logger.info('comment content :{}'.format(comment))

        if get and 'delete_comment' in get:
            logger.info('DELETING COMMENT ...')

mycrm/templates/_breadcrumb.html
{% comment %} <!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">My Dashboard</li>
</ol>
 {% endcomment %}


<!-- Breadcrumbs-->
<ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboards</a>
        </li>
        <li class="breadcrumb-item active">My Dashboard</li>
    </ol>
    <p>{% url 'mycrm:user' %}</p>


{% comment %} 
bread crumb using template for-loop:
{% endcomment %}

mycrm/templates/_navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'mycrm:home' %}">SimpleCRM</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            {% if request.user.is_superuser %}
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
                    <i class="fa fa-fw fa-wrench"></i>
                    <span class="nav-link-text">User Admin</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapseComponents">
                    <li>
                        <a href="{% url 'mycrm:user' %}">User</a>
                    </li>
                    <li>
                        <a href="{% url 'mycrm:register' %}">Register new user</a>
                    </li>
                </ul>
            </li>
            {% else %}
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="{% url 'mycrm:user' %}">
                    <i class="fa fa-fw fa-user"></i>
                    <span class="nav-link-text">User</span>
                </a>
            </li>            
            {% endif %}
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Example Pages">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages" data-parent="#exampleAccordion">
                    <i class="fa fa-fw fa-file"></i>
                    <span class="nav-link-text">Company</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapseExamplePages">
                    <li>
                        <a href="{% url 'mycrm:company' %}">Companies List</a>
                    </li>
                    <li>
                        <a href="{% url 'mycrm:company_add' %}">Add new Company</a>
                    </li>
                    <li>
                        <a href="{% url 'mycrm:company_report' %}">Download PDF Report</a>
                    </li>
                </ul>
            </li>
        </ul>
        
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% comment %} 
            <!-- dropdown alerts -->
            <li class="nav-item dropdown"> 
                <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-envelope"></i>
                    <span class="d-lg-none">Messages
                        <span class="badge badge-pill badge-primary">12 New</span>
                    </span>
                    <span class="indicator text-primary d-none d-lg-block">
                        <i class="fa fa-fw fa-circle"></i>
                    </span>
                </a>
                <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                    <h6 class="dropdown-header">New Messages:</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>David Miller</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>Jane Smith</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>John Doe</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item small" href="#">View all messages</a>
                </div>
            </li>
            {% endcomment %}
            {% comment %}  
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-bell"></i>
                    <span class="d-lg-none">Alerts
                        <span class="badge badge-pill badge-warning">6 New</span>
                    </span>
                    <span class="indicator text-warning d-none d-lg-block">
                        <i class="fa fa-fw fa-circle"></i>
                    </span>
                </a>
                <div class="dropdown-menu" aria-labelledby="alertsDropdown">
                    <h6 class="dropdown-header">New Alerts:</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <span class="text-success">
                            <strong>
                                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <span class="text-danger">
                                <strong>
                                    <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
                                </span>
                                <span class="small float-right text-muted">11:21 AM</span>
                                <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">
                                <span class="text-success">
                                    <strong>
                                        <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
                                    </span>
                                    <span class="small float-right text-muted">11:21 AM</span>
                                    <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item small" href="#">View all alerts</a>
                            </div>
                        </li>
                        {% endcomment %}

                        <li class="nav-item">
                            <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                                <i class="fa fa-fw fa-sign-out"></i>Logout</a>
                            </li>
                        </ul>
                    </div>
                </nav>
                

mycrm/templates/base.html
{% extends "base_layout.html" %}

{% block basecontent %}
    {% include "_navigation.html" %}
    <div class="content-wrapper">

        <!-- content - Page content -->

        {% comment %} {% include "_test_content.html" %} {% endcomment %}
        
        <ol class="breadcrumb">
        {% block breadcrumb %}
        <!-- here is breadcumb view -->
        {% endblock %}
        </ol>

            <!-- messages -->
            <div>
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            <!-- end messages -->

        {% block content %}
        <!-- content - base view for html with side menus -->
        {% endblock %}
        
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <small>Copyright © Your Website 2017</small>
                </div>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="{% url 'mycrm:logout' %}">Logout</a><!-- Logout button screen button -->
                    </div>
                </div>
            </div>
        </div>
        
    </div>
{% endblock %}

mycrm/templates/base_layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SimpleCRM</title>
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    
    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
    
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    
    {% block head %}
    <!-- head - additional header content -->
    {% endblock %}
    
</head>
<body class="fixed-nav sticky-footer bg-dark" id="page-top">

    {% block basecontent %}
        <!-- basecontent -->
    {% endblock %}

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static 'js/sb-admin-datatables.min.js' %}"></script>
    <script src="{% static 'js/sb-admin-charts.min.js' %}"></script>
    
    {% block js %}
    <!-- js - additional java script here -->
    {% endblock %}
</body>

mycrm/templates/register_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block sidebar_content %}
{% include '_users_bar.html' %}
{% endblock %}


{% block content %}

<p>Add user form</p>

<form action="/mycrm/user/register" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" />
</form>


{% endblock %}

mycrm/templates/user.html
{% extends 'base.html' %}


{% block sidebar_content %}
<ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a class="nav-link active" href="#">Users</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Register new user</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="#">Download users list</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Export</a>
    </li>
 </ul>
{% endblock %}


{% block content %}

<p>Users page</p>

{% endblock %}