SimpleCRM/SimpleCRM/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

SimpleCRM/urls.py
'''
App root

'''

#django imports
# from django.conf import settings
from . import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import django.contrib.auth.urls
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/mycrm/login')),
    #crm dashboard
    url(r'^mycrm/', include('mycrm.urls')),
    #password reset pages
    url(r'^accounts/', include('django.contrib.auth.urls')),
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mycrm/urls.py
'''
mycrm urls
'''

#core Django imports
from django.conf.urls import url
from django.contrib.auth import views as auth_views

#Import from current app
from . import views

app_name = 'mycrm'

urlpatterns=[
    #login views
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registration/password_reset_form.html'}, name='password_reset'),
    url(r'^logout/$', views.logout_crm, name="logout"),
    #mycrm views
    url(r'^$', views.UsersList.as_view(), name="home"),
    url(r'^user/$', views.UsersList.as_view(), name="user"),
    url(r'^user/(?P<pk>[0-9]+)/edit$', views.UserEdit.as_view(), name="user_edit"),
    url(r'^user/(?P<pk>[0-9]+)/delete$', views.UserDelete.as_view(), name="user_delete"),
    url(r'^user/register$', views.RegisterUser.as_view(), name="register"),
    #company views
    url(r'^company/$', views.CompaniesListView.as_view(), name="company"),
    url(r'^company/add$', views.CompanyAdd.as_view(), name="company_add"),
    url(r'^company/(?P<pk>[0-9]+)/$', views.CompanyDetailView.as_view(), name="detail"),
    url(r'^company/(?P<pk>[0-9]+)/edit/$', views.CompanyUpdate.as_view(), name="company_edit"),
    url(r'^company/(?P<pk>[0-9]+)/delete/$', views.CompanyDelete.as_view(), name="company_delete"),
    #TODO add company pk here...
    # url(r'^company/addcontact', views.ContactAdd.as_view(), name="contact_add"),
    url(r'^company/(?P<pk>[0-9]+)/addcontact', views.ContactAdd.as_view(), name="contact_add"),
    url(r'^company/(?P<pk>[0-9]+)/editcontact', views.ContactEdit.as_view(), name="edit_contact"),
    url(r'^company/(?P<pk>[0-9]+)/deletecontact', views.ContactDelete.as_view(), name="delete_contact"),
    #TODO add company pk here
    # url(r'^company/addorder', views.OrderAdd.as_view(), name="order_add"),
    url(r'^company/(?P<pk>[0-9]+)/addorder', views.OrderAdd.as_view(), name="order_add"),    
    url(r'^company/(?P<pk>[0-9]+)/orderedit', views.OrderEdit.as_view(), name="order_edit"),
    url(r'^company/report$', views.company_report, name="company_report"),
]

mycrm/models.py
'''
Database models for mycrm
'''
#core Django imports
from django.db import models
from django.contrib.auth.models import User

#local imports
from .validators import validate_phone


class Company(models.Model):
    '''
    Company data, display on company list
    '''
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=4500)
    picture = models.CharField(max_length=500, null=True, default=None)
    # picture = models.ImageField(upload_to="images", blank=True, null=True) #picture field change require delete whole database
    ranking_position = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.name

class Comment(models.Model):
    '''
    Company comment
    related to user and company
    '''
    title = models.CharField(max_length=128, default=None)
    comment = models.TextField(max_length=4000)

    #current time when coment post
    date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User)
    company = models.ForeignKey(Company)

    def __str__(self):
        return self.title

class BusinessCard(models.Model):
    '''
    Business card has user data corresponding to company
    '''
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    phone = models.CharField(max_length=20, validators=[validate_phone])
    company = models.ForeignKey(Company)

    class Meta:
        verbose_name = 'Business Card'
        verbose_name_plural = 'Business Cards'

    def __str__(self):
        return self.name


class Order(models.Model):
    '''
    Order has all orders corresponding to one company. Company can have many orders
    '''
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=2000)
    value = models.DecimalField(max_digits=12, decimal_places=2) #value in euro
    payment_status = models.BooleanField(default=False) #true if client already pait us for order
    date_created = models.DateField() #date created
    project_is_finished = models.BooleanField(default=False) #tells if project is finished
    company = models.ForeignKey(Company) #for who we make project

    @property
    def sum_quantity(self):
        '''
        calculate all bills sum, total display on companies list view
        '''
        total=sum([obj.value for obj in Order.objects.filter(company=self.company.pk)])
        return total

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return self.name

mycrm/views.py
'''
mycrm all views
'''

#core Django imports
from django.contrib import messages
from django.contrib.sessions.backends.db import SessionStore
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth import logout
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Coalesce

#Import from current app
import mycrm.models as models
import mycrm.forms as forms
from logger import logger, logger_user_activity

#Third party libraries import
from reportlab.pdfgen import canvas

#my utilities and libraries
from mycrm.my_utilities import queries, breadcrumb_creator


session = SessionStore()


class UpdateViewWithMessage(UpdateView):
    '''
    Extended Update view contain field:
    my_message - message which displays in green bracket after succesfull delete, user must first set this field
    page_title - title that dispalys in update page header
    '''
    def form_valid(self, form):
        messages.success(self.request, self.my_message)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        #using for create universal template for update views
        context = super().get_context_data()
        context['page_title'] = self.page_title
        return context

class DeleteViewWithMessage(DeleteView):
    '''
    Extended Delete view contain field:
    my_message - message which displays in green bracket after succesfull delete, user must first set this field
    page_title - title that dispalys in update page header
    page_text - text display below page title in <p>page_text</p>
    '''
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.my_message)
        return super().delete(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['page_title'] = self.page_title
        context['page_text'] = '{} {}?'.format(self.page_text, context['object'])
        return context


class CreateViewWithMessage(CreateView):
    '''
    Create view with green popup message after success submit
    Child must overrdte my_message
    '''

    def form_valid(self, form):
        messages.success(self.request, self.my_message)
        return super().form_valid(form)


@login_required
def logout_crm(request):
    '''
    logout current user
    /mycrm/logout
    '''
    logout(request)
    return redirect('mycrm:login')


@login_required
def company_report(request):
    '''
    create pdf report
    company/report
    '''
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'
    p = canvas.Canvas(response, initialFontName='Times-Roman')
    lines = queries.get_companies_report_text()

    page_size = 35
    space = 20
    for i,line in enumerate(lines):
        p.drawString(50, 800-(i % page_size)*space, line)
        if (i+1) % page_size == 0:
            p.showPage()
    p.save()
    return response


class UsersList(LoginRequiredMixin, ListView):
    '''
    page with users table
    mycrm/user/
    '''
    template_name = 'user/user.html'
    context_object_name = 'users'
    model = User


class RegisterUser(LoginRequiredMixin, CreateViewWithMessage):
    '''
    registration page
    mycrm/user/register
    '''
    form_class = forms.SignUpForm
    model = User #user from django
    template_name = 'mycrm/user_register.html'
    success_url = reverse_lazy('mycrm:user')
    my_message = 'User created succesfully!'

class UserEdit(LoginRequiredMixin, PermissionRequiredMixin, UpdateViewWithMessage):
    '''
    user edit page
    mycrm/user/<user_id>/edit
    '''
    permission_required = 'auth.change_user'
    form_class = forms.EditUserForm
    model = User
    template_name = 'mycrm/update_view.html'
    success_url = reverse_lazy('mycrm:user')
    my_message = 'Update user succesfully'
    page_title = 'Edit User:'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('Home', reverse_lazy('mycrm:home'))
        breadcrumb.append_page('User', reverse_lazy('mycrm:user'))
        breadcrumb.append_active_page('Edit User')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context



class UserDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteViewWithMessage):
    '''
    user delete page
    mycrm/user/<user_id>/delete
    '''
    permission_required = 'auth.delete_user'
    model = User
    template_name = 'mycrm/delete_view.html'
    success_url = reverse_lazy('mycrm:user')
    my_message = 'You delete user succesfully!'
    page_title = 'Delete user'
    page_text = 'Are you sure delete user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('User', reverse_lazy('mycrm:user'))
        breadcrumb.append_active_page('Delete User')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context

class CompaniesListView(LoginRequiredMixin, ListView):
    '''
    page with companies table
    mycrm/company
    '''
    model = models.Company
    template_name = 'mycrm/company.html'

    def get_context_data(self, **kwargs):
        context = super(CompaniesListView, self).get_context_data(**kwargs)
        context['tomek']= 'przyklad'
        return context

    def get_queryset(self): # for filtering
        '''
        Using for filtering (search filed)
        :return: filtered queryset
        '''
        qs= super().get_queryset()
        var = self.request.GET.get('q')
        if var:
            return qs.filter(name__startswith=var)
        return qs


class CompanyUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateViewWithMessage):
    '''
    company update page
    mycrm/company/<company_id>/edit
    '''
    permission_required = 'mycrm.change_company'
    form_class = forms.CompanyForm
    model = models.Company
    template_name = 'mycrm/update_view.html'
    success_url = reverse_lazy('mycrm:company')
    my_message = 'You change company data succesfully!'
    page_title = 'Edit company:'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('Home', reverse_lazy('mycrm:home'))
        breadcrumb.append_page('Company', reverse_lazy('mycrm:company'))
        breadcrumb.append_active_page('Edit Company')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context


class CompanyDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteViewWithMessage):
    '''
    company delete page
    mycrm/<company_id>/delete
    '''
    permission_required = 'mycrm.delete_company'
    model = models.Company
    success_url = reverse_lazy('mycrm:company')
    template_name = 'mycrm/delete_view.html'
    page_title = 'Delete company'
    page_text = 'Are you sure you want delete company:'
    my_message = 'You delete company succesfully!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        breadcrumb = breadcrumb_creator.BreadcrumbCreator()
        breadcrumb.append_page('Home', reverse_lazy('mycrm:home'))
        breadcrumb.append_page('Company', reverse_lazy('mycrm:company'))
        breadcrumb.append_active_page('Delete Company')
        context['breadcrumb'] = breadcrumb.get_pages()
        return context


class CompanyDetailView(LoginRequiredMixin, DetailView):
    '''
    company detail view:
    description, contacts table, orders table
    comments - variable ith all comments sorted by date
    has count variables for using in template:
    comments_count
    contacts_count
    order_count
    mycrm/company/<company_id>/

    '''
    model = models.Company
    template_name = 'mycrm/company_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['comments'] = models.Comment.objects.all()
        current_company = context['object']
        nonordered_comments = current_company.comment_set.all()
        context['comments'] = nonordered_comments.order_by(Coalesce('date', 'pk').desc())
        context['comments_count'] = current_company.comment_set.count()
        context['contacts_count'] = current_company.businesscard_set.count()
        context['order_count'] = current_company.order_set.count()
        logger.info(context['comments'])
        return context

    def get(self, request, *args, **kwargs):
        get = request.GET
        if get and 'comm' in get and 'title' in get:
            logger.info('ADDING COMMENT ...')
            logger.info('REQEST ->   {}'.format(request))
            logger.info('kwargs  {} user {} args {}'.format(kwargs, request.user, args))
            title = request.GET['title']
            comm = request.GET['comm']
            current_company = models.Company.objects.get(pk=kwargs['pk'])
            # current_company = self.get_context_data()['object'] #not works
            #pk mam w request current_company.comment_set - comment_set.comment - wyciągam coś z comment
            comment = models.Comment(company=current_company, user=request.user, title=title, comment=comm)
            comment.save()
            logger.info('comment content :{}'.format(comment))

        if get and 'delete_comment' in get:
            logger.info('DELETING COMMENT ...')

mycrm/templates/mycrm/includes/_about_tab.html
{% load staticfiles %}


{% comment %} <div class="card mb-3">
    
    <div class="container-fluid jumbotron">
        <div>
            <h2 class="text-center">Company name: </h2>
            <h3 class="text-center">{{ company }}</h3>
            <h2 class="text-center">Logo:</h2>
            <div class="text-center" style="padding-bottom: 22px; padding-top=22px;">
                <img class="img rounded text-center" onerror="this.src='{% static 'img/no_image.png' %}';"
                alt="ghf"
                height="200"
                src="{{ company.picture }}"/>
            </div>
            <p>
                <h2 class="text-center">About company:</h2>
                <h3 class="text-center">{{ company.description }}</h3>
            </p>
            <h2 class="text-center">Number of employees</h2>
            <h3 class="text-center">{{ company.businesscard_set.count }}</h3>
        </div>
    </div>   
</div> {% endcomment %}


  <!-- tab header -->
  <div class="card mb-3">
    <div class="card-header"><i class="fa fa-home h1"></i> About:</div>
    
    <div class="card-body graybg container-fluid">
      
      <!-- logo -->
        <div class="card mylogo">
          <div class="card-header">Company Logo:</div>
          <div class="card-body mylogo2">
            <img class="img rounded text-center" onerror="this.src='{% static 'img/no_image.png' %}';"
            alt="ghf"
            width="230"
            src="{{ company.picture }}"/>
         </div>
          </div>

        
        <!-- description -->
          <div class="card mycompany">
            <div class="card-header">Company description:</div>
            <div class="card-body text-justify">
                {{ company.description }}            
            </div>
          </div>


          <!-- nuber of employers -->
          <div class="card cardEmployers">
            <div class="card-header">Number current of employers:</div>
            <div class="card-body mylogo2 text-justify">
              Number of company contacts is <strong>{{ company.businesscard_set.count }}</strong>.
            </div>
          </div>
        
      </div>
      </div>

mycrm/templates/mycrm/includes/_comments_tab.html
{% load staticfiles %}
<!-- comment tab -->


<div class="tab-pane" id="comments" role="tabpanel">
    
    <form class="comment-form" method="get">
        {% csrf_token %}
        <div class="form-group">
            <label class="col-form-label" for="formGroupExampleInput">Title</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Title" name="title">
        </div>
        <div class="form-group">
            <label class="col-form-label" for="formGroupExampleInput2">Comment</label>
            <textarea rows="5" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Type your coment here ..." name="comm"></textarea>
        </div>
        <input type="submit" class="btn btn-primary" value="Submit comment">
    </form>
    
    {% for comment in comments %}
    
    <div class="jumbotron comment">
        <h3>{{ comment.title }}</h3>
        <div class="col-sm-3">{{ comment.comment }}</div> 
        <!-- deletebutton -->
        <div align="right">
            <!-- Button trigger modal -->
            <button type="button" align="left" class="btn btn-danger deleteval" data-toggle="modal" data-target="#modelId" value="{{comment.pk}}" ><!-- little hack get comment from here -->
                Delete
            </button>
            
            <!-- Delete messagebox Modal -->
            <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="modelTitleId">Warning!</h4>
                        </div>
                        <div class="modal-body">
                            Do you really want to delete this comment?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                            <form method="get">
                                <button type="submit" align="left" class="btn btn-danger deletebutton" name="delete_comment">Yes</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            
            
        </div>
        <div align="left"> 
            <a class="secondary">Date: {{ comment.date }}</a> 
            <a class="secondary">User: {{ comment.user }}</a> 
            
        </div>
    </div> 
    {% endfor %}            
</div>

mycrm/templates/mycrm/includes/_contacts_tab.html
{% load staticfiles %}


<!-- Table with contacts -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Contacts:</div>
        <a class="btn btn-warning" href="{% url 'mycrm:contact_add' company.pk %}"><i class="fa fa-user-plus"></i> Add contact</a>
        <div class="card-body">
            <div class="table-responsive">
                
                
                
                <table class="table table-bordered" id="ta" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>contact name</th>
                            <th>phone number</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>#</th>
                            <th>contact name</th>
                            <th>phone number</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for card in company.businesscard_set.all %}
                        <tr class="active">
                            <td>{{ forloop.counter }}</td>
                            <td><a class="btn btn-light" href="{% url 'mycrm:edit_contact' card.pk %}"><i
                                class="fa fa-address-card-o" aria-hidden="true"></i></a>
                                <a class="btn btn-primary" href="{% url 'mycrm:delete_contact' card.pk %}"
                                role="button"><i class="fa fa-trash" aria-hidden="true"></i></a>
                                {{ card.name }} {{ card.last_name }} </td>
                                <td>{{ card.phone }}</td>
                            </tr>
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>
                
            </div>
        </div>
        

mycrm/templates/mycrm/includes/_orders_tab.html
{% load staticfiles %}


<!-- Table with contacts -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Clients orders:
    </div>
        <a class="btn btn-success" href="{% url 'mycrm:order_add' company.pk %}"><i class="fa fa-plus"></i> Add order</a>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Value</th>
                            <th>Payment status</th>
                            <th>date created</th>
                            <th>Finished</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Value</th>
                            <th>Payment status</th>
                            <th>date created</th>
                            <th>Finished</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for order in company.order_set.all %}
                        <tr class="active">
                            <td>{{ forloop.counter }}</td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'mycrm:order_edit' order.pk %}"
                                role="button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                {{ order.name }}
                            </td>
                            <td>{{ order.description }}</td>
                            <td>{{ order.value }}</td>
                            <td>
                                {% if order.payment_status %}
                                <i class="fa fa-check" style="font-size: 35px; color: #00a800;"></i>
                                {% else %}
                                <i class="fa fa-times" style="font-size: 35px; color: red;"></i>
                                {% endif %}
                            </td>
                            <td>{{ order.date_created }}</td>
                            <td>
                                {% if order.project_is_finished %}
                                <i class="fa fa-check" style="font-size: 35px; color: #00a800;"></i>
                                {% else %}
                                <i class="fa fa-times" style="font-size: 35px; color: red;"></i>
                                {% endif %}
                                
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    